[build]
  command="ng build"
  publish="dist/playmobox"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# [[plugins]]
#  package = "netlify-plugin-cypress"
#
#  [plugins.inputs]
#    enable = "[[context]] == 'deploy-preview'"
